### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by chpio** [academe/proj4php#2]
Hi,

it would be nice if this package would have a version.
You can add a version by tagging. The tag should have this format: a "v" followed by a [semver](http://semver.org/) eg: "v0.0.1"

thank you :)

**Comment by judgej** [comment]
Nice if I could get around to finishing it too. Just trying to find the time.

**Comment by phaza** [comment]
+1. I dislike having dev-master in my composer.json

**Comment by judgej** [comment]
Does release 0.6.0 work for you? It is labelled as a "pre-release" but that shouldn't affect the dev/release status, if I understand correctly.

**Comment by phaza** [comment]
Sorry, I wasn't making myself clear, but pointing to dev-master or a tag on github doesn't make much difference.

I really would like to see it here: https://packagist.org/packages/academe/

**Comment by judgej** [comment]
Ah, I understand - it's about not pointing to a revision control repository at all. I'll sort that out.

**Comment by judgej** [comment]
Here you go:

https://packagist.org/packages/academe/proj4php

There is another proj4php package there, developed on sourceforge. I've not seen that package before and have no idea if it is more active than this one. I do fully intend on getting back to this later in the year, but welcome all pull requests or suggestions in the meantime.

**Comment by phaza** [comment]
Thanks!

Yeah, I know there's another, but your code base is much cleaner, so I prefer yours.

**Comment by judgej** [comment]
Cool. Any fixes you do - just fire them back :-)
