### ISSUE TITLE
call Mgrs::forward leads to the crash of the laravel application

### ISSUE THREAD

**Issue by oddssoft** [academe/proj4php#5]
Hello!
I have installed version by composer (0.6.1).

Calling Mgrs :: forward results in an error in Laravel:
Academic \ Proj4Php \ Mgrs \ Mgrs :: getLetter100kId () should not be called \ academe \ proj4php \ src \ Mgrs \ Mgrs.php at the line # 253

code changes from

protected function getLetter100kId ($ column, $ row, $ parm) {
to

protected statics function getLetter100kId ($ column, $ row, $ parm) {

solves this problem.

**Comment by odyswise** [comment]
Could you possibly update composer pakage's version for supporting this change, please?
